runtime: java17
instance_class: F2
entrypoint: java -jar target/helloworld-0.0.1-SNAPSHOT.jar


automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
  
handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always